// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Fish

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_background;
extern lv_obj_t * ui_list1;
extern void ui_event_wifiButton(lv_event_t * e);
extern lv_obj_t * ui_wifiButton;
extern lv_obj_t * ui_wifiLab;
extern void ui_event_waveButton(lv_event_t * e);
extern lv_obj_t * ui_waveButton;
extern lv_obj_t * ui_waveLab;
extern lv_obj_t * ui_WifiPanel;
extern lv_obj_t * ui_SSIDLabel;
extern void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_PASSWORDLabel;
extern void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_ConnectButton;
extern lv_obj_t * ui_Label3;
extern void ui_event_backbutton(lv_event_t * e);
extern lv_obj_t * ui_backbutton;
extern lv_obj_t * ui_XImage;
extern lv_obj_t * ui_InformationLabel;
extern lv_obj_t * ui_InforLabel;
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_wavePanel;
extern void ui_event_backbutton2(lv_event_t * e);
extern lv_obj_t * ui_backbutton2;
extern lv_obj_t * ui_XImage2;
extern lv_obj_t * ui_TRIImage;
extern lv_obj_t * ui_SQUAmage;
extern lv_obj_t * ui_SINImage;
extern void ui_event_SwitchA(lv_event_t * e);
extern lv_obj_t * ui_SwitchA;
extern void ui_event_SwitchB(lv_event_t * e);
extern lv_obj_t * ui_SwitchB;
extern void ui_event_SwitchC(lv_event_t * e);
extern lv_obj_t * ui_SwitchC;
extern lv_obj_t * ui_LabelSquare_Wave;
extern lv_obj_t * ui_LabelSine_Wave;
extern lv_obj_t * ui_LabelTriangle_Wave;
extern lv_obj_t * ui_LabelFreq;
extern lv_obj_t * ui_LabelVpp;
extern lv_obj_t * ui_ButtonCHANGE;
extern lv_obj_t * ui_LabelCHANGE;
extern void ui_event_TextAreaFREQ(lv_event_t * e);
extern lv_obj_t * ui_TextAreaFREQ;
extern void ui_event_TextAreaVPP(lv_event_t * e);
extern lv_obj_t * ui_TextAreaVPP;
extern lv_obj_t * ui_Keyboard3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

