// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Fish

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_background = NULL;
lv_obj_t * ui_list1 = NULL;
lv_obj_t * ui_wifiButton = NULL;
lv_obj_t * ui_wifiLab = NULL;
lv_obj_t * ui_waveButton = NULL;
lv_obj_t * ui_waveLab = NULL;
lv_obj_t * ui_WifiPanel = NULL;
lv_obj_t * ui_SSIDLabel = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_PASSWORDLabel = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_ConnectButton = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_backbutton = NULL;
lv_obj_t * ui_XImage = NULL;
lv_obj_t * ui_InformationLabel = NULL;
lv_obj_t * ui_InforLabel = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
lv_obj_t * ui_wavePanel = NULL;
lv_obj_t * ui_backbutton2 = NULL;
lv_obj_t * ui_XImage2 = NULL;
lv_obj_t * ui_TRIImage = NULL;
lv_obj_t * ui_SQUAmage = NULL;
lv_obj_t * ui_SINImage = NULL;
lv_obj_t * ui_SwitchA = NULL;
lv_obj_t * ui_SwitchB = NULL;
lv_obj_t * ui_SwitchC = NULL;
lv_obj_t * ui_LabelSquare_Wave = NULL;
lv_obj_t * ui_LabelSine_Wave = NULL;
lv_obj_t * ui_LabelTriangle_Wave = NULL;
lv_obj_t * ui_LabelFreq = NULL;
lv_obj_t * ui_LabelVpp = NULL;
lv_obj_t * ui_ButtonCHANGE = NULL;
lv_obj_t * ui_LabelCHANGE = NULL;
lv_obj_t * ui_TextAreaFREQ = NULL;
lv_obj_t * ui_TextAreaVPP = NULL;
lv_obj_t * ui_Keyboard3 = NULL;
// event funtions
void ui_event_wifiButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        slideout_Animation(ui_WifiPanel, 0);
    }
}

void ui_event_waveButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        slideout_Animation(ui_wavePanel, 0);
    }
}

void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_TextArea1);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        keyboardslide_Animation(ui_Keyboard2, 0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        keyboardslideout_Animation(ui_Keyboard2, 0);
    }
}

void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_TextArea2);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        keyboardslide_Animation(ui_Keyboard2, 0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        keyboardslideout_Animation(ui_Keyboard2, 0);
    }
}

void ui_event_backbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        slidein_Animation(ui_WifiPanel, 0);
    }
}

void ui_event_backbutton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        slidein_Animation(ui_wavePanel, 0);
    }
}

void ui_event_SwitchA(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_state_modify(ui_SwitchB, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_SwitchC, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_SwitchB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_state_modify(ui_SwitchA, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_SwitchC, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_SwitchC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_state_modify(ui_SwitchB, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_SwitchA, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_TextAreaFREQ(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard3,  ui_TextAreaFREQ);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        keyboardslide_Animation(ui_Keyboard3, 0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        keyboardslideout_Animation(ui_Keyboard3, 0);
    }
}

void ui_event_TextAreaVPP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard3,  ui_TextAreaVPP);
    }
    if(event_code == LV_EVENT_FOCUSED) {
        keyboardslide_Animation(ui_Keyboard3, 0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        keyboardslideout_Animation(ui_Keyboard3, 0);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_background = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_background, &ui_img_tsuki_ni_yorisou_otome_no_sahou_png);
    lv_obj_set_width(ui_background, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_background, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_background, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_background, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_background, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_list1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_list1, 100);
    lv_obj_set_height(ui_list1, 480);
    lv_obj_set_align(ui_list1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_flex_flow(ui_list1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_list1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_list1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_list1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_list1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_list1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_list1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_list1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_list1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_list1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_list1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiButton = lv_btn_create(ui_list1);
    lv_obj_set_width(ui_wifiButton, 95);
    lv_obj_set_height(ui_wifiButton, 50);
    lv_obj_set_x(ui_wifiButton, -47);
    lv_obj_set_y(ui_wifiButton, 138);
    lv_obj_set_align(ui_wifiButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifiButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wifiButton, lv_color_hex(0x349ADA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifiButton, lv_color_hex(0x00FFF0), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_wifiButton, 155, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_wifiLab = lv_label_create(ui_wifiButton);
    lv_obj_set_width(ui_wifiLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifiLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiLab, "WIFI");

    ui_waveButton = lv_btn_create(ui_list1);
    lv_obj_set_width(ui_waveButton, 95);
    lv_obj_set_height(ui_waveButton, 50);
    lv_obj_set_x(ui_waveButton, -353);
    lv_obj_set_y(ui_waveButton, -176);
    lv_obj_set_align(ui_waveButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_waveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_waveButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_waveButton, lv_color_hex(0x349ADA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_waveButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_waveButton, lv_color_hex(0x00FFF0), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_waveButton, 155, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_waveLab = lv_label_create(ui_waveButton);
    lv_obj_set_width(ui_waveLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_waveLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_waveLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_waveLab, "WAVE");

    ui_WifiPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_WifiPanel, 700);
    lv_obj_set_height(ui_WifiPanel, lv_pct(100));
    lv_obj_set_x(ui_WifiPanel, 700);
    lv_obj_set_y(ui_WifiPanel, 0);
    lv_obj_set_align(ui_WifiPanel, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_WifiPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiPanel, lv_color_hex(0xD6F79E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiPanel, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSIDLabel = lv_label_create(ui_WifiPanel);
    lv_obj_set_width(ui_SSIDLabel, 50);
    lv_obj_set_height(ui_SSIDLabel, 30);
    lv_obj_set_x(ui_SSIDLabel, -256);
    lv_obj_set_y(ui_SSIDLabel, -193);
    lv_obj_set_align(ui_SSIDLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SSIDLabel, "SSID");
    lv_obj_set_style_text_font(ui_SSIDLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_WifiPanel);
    lv_obj_set_width(ui_TextArea1, 150);
    lv_obj_set_height(ui_TextArea1, 35);
    lv_obj_set_x(ui_TextArea1, -160);
    lv_obj_set_y(ui_TextArea1, -200);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");

    ui_PASSWORDLabel = lv_label_create(ui_WifiPanel);
    lv_obj_set_width(ui_PASSWORDLabel, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_PASSWORDLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PASSWORDLabel, -290);
    lv_obj_set_y(ui_PASSWORDLabel, -141);
    lv_obj_set_align(ui_PASSWORDLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PASSWORDLabel, "PASSWORD");
    lv_obj_set_style_text_font(ui_PASSWORDLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea2 = lv_textarea_create(ui_WifiPanel);
    lv_obj_set_width(ui_TextArea2, 150);
    lv_obj_set_height(ui_TextArea2, 35);
    lv_obj_set_x(ui_TextArea2, -160);
    lv_obj_set_y(ui_TextArea2, -143);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");

    ui_ConnectButton = lv_btn_create(ui_WifiPanel);
    lv_obj_set_width(ui_ConnectButton, 80);
    lv_obj_set_height(ui_ConnectButton, 38);
    lv_obj_set_x(ui_ConnectButton, -4);
    lv_obj_set_y(ui_ConnectButton, -200);
    lv_obj_set_align(ui_ConnectButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConnectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConnectButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConnectButton, lv_color_hex(0xFD5D5D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConnectButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConnectButton, lv_color_hex(0xFFC2C2), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ConnectButton, 200, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label3 = lv_label_create(ui_ConnectButton);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "CONNECT");

    ui_backbutton = lv_btn_create(ui_WifiPanel);
    lv_obj_set_width(ui_backbutton, 50);
    lv_obj_set_height(ui_backbutton, 50);
    lv_obj_set_x(ui_backbutton, 313);
    lv_obj_set_y(ui_backbutton, 205);
    lv_obj_set_align(ui_backbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_XImage = lv_img_create(ui_backbutton);
    lv_img_set_src(ui_XImage, &ui_img_1033704984);
    lv_obj_set_width(ui_XImage, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_XImage, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_XImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_XImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_XImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_XImage, 50);

    ui_InformationLabel = lv_label_create(ui_WifiPanel);
    lv_obj_set_width(ui_InformationLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InformationLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InformationLabel, -279);
    lv_obj_set_y(ui_InformationLabel, -79);
    lv_obj_set_align(ui_InformationLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InformationLabel, "Information");
    lv_obj_set_style_text_font(ui_InformationLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InforLabel = lv_label_create(ui_WifiPanel);
    lv_obj_set_width(ui_InforLabel, 180);
    lv_obj_set_height(ui_InforLabel, 50);
    lv_obj_set_x(ui_InforLabel, -114);
    lv_obj_set_y(ui_InforLabel, -63);
    lv_obj_set_align(ui_InforLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InforLabel, "");
    lv_obj_set_style_radius(ui_InforLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_InforLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InforLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard2 = lv_keyboard_create(ui_WifiPanel);
    lv_obj_set_width(ui_Keyboard2, 500);
    lv_obj_set_height(ui_Keyboard2, 220);
    lv_obj_set_x(ui_Keyboard2, 1000);
    lv_obj_set_y(ui_Keyboard2, 16);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    ui_wavePanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_wavePanel, 700);
    lv_obj_set_height(ui_wavePanel, lv_pct(100));
    lv_obj_set_x(ui_wavePanel, 800);
    lv_obj_set_y(ui_wavePanel, 0);
    lv_obj_set_align(ui_wavePanel, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_wavePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_wavePanel, lv_color_hex(0xD6F79E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wavePanel, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backbutton2 = lv_btn_create(ui_wavePanel);
    lv_obj_set_width(ui_backbutton2, 50);
    lv_obj_set_height(ui_backbutton2, 50);
    lv_obj_set_x(ui_backbutton2, 313);
    lv_obj_set_y(ui_backbutton2, 205);
    lv_obj_set_align(ui_backbutton2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbutton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backbutton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_XImage2 = lv_img_create(ui_backbutton2);
    lv_img_set_src(ui_XImage2, &ui_img_1033704984);
    lv_obj_set_width(ui_XImage2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_XImage2, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_XImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_XImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_XImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_XImage2, 50);

    ui_TRIImage = lv_img_create(ui_wavePanel);
    lv_img_set_src(ui_TRIImage, &ui_img_gemini_generated_image_flbzrbflbzrbflbz_png);
    lv_obj_set_width(ui_TRIImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TRIImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TRIImage, -250);
    lv_obj_set_y(ui_TRIImage, 0);
    lv_obj_set_align(ui_TRIImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TRIImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TRIImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SQUAmage = lv_img_create(ui_wavePanel);
    lv_img_set_src(ui_SQUAmage, &ui_img_gemini_generated_image_jb1wkajb1wkajb1w_png);
    lv_obj_set_width(ui_SQUAmage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SQUAmage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SQUAmage, -250);
    lv_obj_set_y(ui_SQUAmage, 166);
    lv_obj_set_align(ui_SQUAmage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SQUAmage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SQUAmage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SINImage = lv_img_create(ui_wavePanel);
    lv_img_set_src(ui_SINImage, &ui_img_mini1_png);
    lv_obj_set_width(ui_SINImage, 120);
    lv_obj_set_height(ui_SINImage, 65);
    lv_obj_set_x(ui_SINImage, -250);
    lv_obj_set_y(ui_SINImage, -166);
    lv_obj_set_align(ui_SINImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SINImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SINImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchA = lv_switch_create(ui_wavePanel);
    lv_obj_set_width(ui_SwitchA, 50);
    lv_obj_set_height(ui_SwitchA, 25);
    lv_obj_set_x(ui_SwitchA, -150);
    lv_obj_set_y(ui_SwitchA, -166);
    lv_obj_set_align(ui_SwitchA, LV_ALIGN_CENTER);

    ui_SwitchB = lv_switch_create(ui_wavePanel);
    lv_obj_set_width(ui_SwitchB, 50);
    lv_obj_set_height(ui_SwitchB, 25);
    lv_obj_set_x(ui_SwitchB, -150);
    lv_obj_set_y(ui_SwitchB, 0);
    lv_obj_set_align(ui_SwitchB, LV_ALIGN_CENTER);

    ui_SwitchC = lv_switch_create(ui_wavePanel);
    lv_obj_set_width(ui_SwitchC, 50);
    lv_obj_set_height(ui_SwitchC, 25);
    lv_obj_set_x(ui_SwitchC, -150);
    lv_obj_set_y(ui_SwitchC, 166);
    lv_obj_set_align(ui_SwitchC, LV_ALIGN_CENTER);

    ui_LabelSquare_Wave = lv_label_create(ui_wavePanel);
    lv_obj_set_width(ui_LabelSquare_Wave, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSquare_Wave, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSquare_Wave, -260);
    lv_obj_set_y(ui_LabelSquare_Wave, 122);
    lv_obj_set_align(ui_LabelSquare_Wave, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSquare_Wave, "Square Wave");

    ui_LabelSine_Wave = lv_label_create(ui_wavePanel);
    lv_obj_set_width(ui_LabelSine_Wave, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSine_Wave, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSine_Wave, -270);
    lv_obj_set_y(ui_LabelSine_Wave, -210);
    lv_obj_set_align(ui_LabelSine_Wave, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSine_Wave, "Sine Wave");

    ui_LabelTriangle_Wave = lv_label_create(ui_wavePanel);
    lv_obj_set_width(ui_LabelTriangle_Wave, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTriangle_Wave, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTriangle_Wave, -256);
    lv_obj_set_y(ui_LabelTriangle_Wave, -44);
    lv_obj_set_align(ui_LabelTriangle_Wave, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTriangle_Wave, "Triangle Wave");

    ui_LabelFreq = lv_label_create(ui_wavePanel);
    lv_obj_set_width(ui_LabelFreq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFreq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFreq, -79);
    lv_obj_set_y(ui_LabelFreq, -190);
    lv_obj_set_align(ui_LabelFreq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFreq, "Freq");

    ui_LabelVpp = lv_label_create(ui_wavePanel);
    lv_obj_set_width(ui_LabelVpp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVpp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVpp, 121);
    lv_obj_set_y(ui_LabelVpp, -190);
    lv_obj_set_align(ui_LabelVpp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVpp, "Vpp");

    ui_ButtonCHANGE = lv_btn_create(ui_wavePanel);
    lv_obj_set_width(ui_ButtonCHANGE, 46);
    lv_obj_set_height(ui_ButtonCHANGE, 141);
    lv_obj_set_x(ui_ButtonCHANGE, 304);
    lv_obj_set_y(ui_ButtonCHANGE, -142);
    lv_obj_set_align(ui_ButtonCHANGE, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonCHANGE, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonCHANGE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonCHANGE, lv_color_hex(0xF197DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonCHANGE, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCHANGE = lv_label_create(ui_ButtonCHANGE);
    lv_obj_set_width(ui_LabelCHANGE, 12);
    lv_obj_set_height(ui_LabelCHANGE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelCHANGE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCHANGE, "CHANGE");

    ui_TextAreaFREQ = lv_textarea_create(ui_wavePanel);
    lv_obj_set_width(ui_TextAreaFREQ, 150);
    lv_obj_set_height(ui_TextAreaFREQ, 35);
    lv_obj_set_x(ui_TextAreaFREQ, -25);
    lv_obj_set_y(ui_TextAreaFREQ, -160);
    lv_obj_set_align(ui_TextAreaFREQ, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaFREQ, "Placeholder...");

    ui_TextAreaVPP = lv_textarea_create(ui_wavePanel);
    lv_obj_set_width(ui_TextAreaVPP, 150);
    lv_obj_set_height(ui_TextAreaVPP, 35);
    lv_obj_set_x(ui_TextAreaVPP, 178);
    lv_obj_set_y(ui_TextAreaVPP, -160);
    lv_obj_set_align(ui_TextAreaVPP, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaVPP, "Placeholder...");

    ui_Keyboard3 = lv_keyboard_create(ui_wavePanel);
    lv_obj_set_width(ui_Keyboard3, 408);
    lv_obj_set_height(ui_Keyboard3, 174);
    lv_obj_set_x(ui_Keyboard3, 1000);
    lv_obj_set_y(ui_Keyboard3, 33);
    lv_obj_set_align(ui_Keyboard3, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_wifiButton, ui_event_wifiButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_waveButton, ui_event_waveButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backbutton, ui_event_backbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backbutton2, ui_event_backbutton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchA, ui_event_SwitchA, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchB, ui_event_SwitchB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchC, ui_event_SwitchC, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaFREQ, ui_event_TextAreaFREQ, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaVPP, ui_event_TextAreaVPP, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_background = NULL;
    ui_list1 = NULL;
    ui_wifiButton = NULL;
    ui_wifiLab = NULL;
    ui_waveButton = NULL;
    ui_waveLab = NULL;
    ui_WifiPanel = NULL;
    ui_SSIDLabel = NULL;
    ui_TextArea1 = NULL;
    ui_PASSWORDLabel = NULL;
    ui_TextArea2 = NULL;
    ui_ConnectButton = NULL;
    ui_Label3 = NULL;
    ui_backbutton = NULL;
    ui_XImage = NULL;
    ui_InformationLabel = NULL;
    ui_InforLabel = NULL;
    ui_Keyboard2 = NULL;
    ui_wavePanel = NULL;
    ui_backbutton2 = NULL;
    ui_XImage2 = NULL;
    ui_TRIImage = NULL;
    ui_SQUAmage = NULL;
    ui_SINImage = NULL;
    ui_SwitchA = NULL;
    ui_SwitchB = NULL;
    ui_SwitchC = NULL;
    ui_LabelSquare_Wave = NULL;
    ui_LabelSine_Wave = NULL;
    ui_LabelTriangle_Wave = NULL;
    ui_LabelFreq = NULL;
    ui_LabelVpp = NULL;
    ui_ButtonCHANGE = NULL;
    ui_LabelCHANGE = NULL;
    ui_TextAreaFREQ = NULL;
    ui_TextAreaVPP = NULL;
    ui_Keyboard3 = NULL;

}
