// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Fish

#ifndef _FISH_UI_H
#define _FISH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * slideout_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * keyboardslide_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * slidein_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * keyboardslideout_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_tsuki_ni_yorisou_otome_no_sahou_png);    // assets/Tsuki ni Yorisou Otome no Sahou.png
LV_IMG_DECLARE(ui_img_1033704984);    // assets/a-21chahao.png
LV_IMG_DECLARE(
    ui_img_gemini_generated_image_flbzrbflbzrbflbz_png);    // assets/Gemini_Generated_Image_flbzrbflbzrbflbz.png
LV_IMG_DECLARE(
    ui_img_gemini_generated_image_jb1wkajb1wkajb1w_png);    // assets/Gemini_Generated_Image_jb1wkajb1wkajb1w.png
LV_IMG_DECLARE(ui_img_mini1_png);    // assets/mini1.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
